#log4j.rootLogger=DEBUG,CONSOLE,LOG
log4j.rootLogger=DEBUG,LOG
log4j.addivity.org.apache=true


#log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
#log4j.appender.CONSOLE.Threshold=DEBUG
#log4j.appender.CONSOLE.Target=System.out
#log4j.appender.CONSOLE.Encoding=UTF-8
#log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
#log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy/MM/dd HH:mm:ss}---%m%n
#log4j.appender.CONSOLE.layout.ConversionPattern=[framework] %d - %c -%-4r [%t] %-5p--- %m%n

log4j.appender.LOG=org.apache.log4j.RollingFileAppender
log4j.appender.LOG.File=${catalina.home}/logs/framework.log
log4j.appender.LOG.Encoding=UTF-8
log4j.appender.LOG.Threshold=DEBUG
log4j.appender.LOG.MaxFileSize=10MB
log4j.appender.LOG.rollfile.MaxBackupIndex=10
#log4j.appender.LOG.DatePattern='.'yyyy-MM-dd
log4j.appender.LOG.layout=org.apache.log4j.PatternLayout
log4j.appender.LOG.layout.ConversionPattern=%d{ABSOLUTE} %5p %c{1}:%L : %m%n

log4j.logger.com.ibatis=INFO   
log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=INFO 
log4j.logger.com.ibatis.common.jdbc.ScriptRunner=INFO   
log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate=INFO   
log4j.logger.java.sql.Connection=DEBUG   
log4j.logger.java.sql.Statement=DEBUG   
log4j.logger.java.sql.PreparedStatement=DEBUG   
log4j.logger.java.sql.ResultSet=INFO

log4j.logger.org.springframework=ERROR

log4j.logger.com.opensymphony.xwork2=ERROR

log4j.logger.org.apache.struts2=ERROR

